### ISSUE TITLE
Secrets Format (MG)

### ISSUE THREAD

**Issue by tanya-jp** [rnorouziani/3D-H3C#40]
Based on the [MG Checklist](https://github.com/rnorouziani/3D-H3C/blob/main/docs/Checklists/MG-Checklist.pdf), secrets are nouns (generally). So, I think it is better to change your secrets, specially the ones for M2 and M5, and make them shorter.

**Comment by rnorouziani** [comment]
Thank you so much for your feedback. I assume a noun cannot explain what these modules' secrets are.
