### ISSUE TITLE
VnV Review: Lettered List

### ISSUE THREAD

**Issue by Tan630** [rnorouziani/3D-H3C#48]
Please consider using a lettered list [1] when writing multiple items. As an example, instead of writing _... reviews and the instructors evaluate the codebase's readability, modularity, and adherence to coding standards, identifying ..._, please consider  _... reviews and the instructors evaluate the codebase's **(a)** readability, **(b)** modularity, and **(c)** adherence to coding standards, identifying ..._

I do appreciate that you use serial commas. You might already know this (lettered lists) and deliberately chose to not use it. In that case my suggestion would be redundant.

[1] https://apastyle.apa.org/style-grammar-guidelines/lists/lettered

**Comment by rnorouziani** [comment]
Thank you so much for your suggestion. Due to consistency with other parts of my writing I prefer to not change this part of this document.
